##### login #####
PUT http://192.168.100.9:8080/login
Content-Type: application/json

{
    "hallTicket": "123ABC456XYZ780",
    "email": "abc0@xyz.com" 
}

##### startExam #####
GET http://192.168.100.9:8080/startExam
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTZXNzaW9uSWQiOjEyLCJFeGFtSWQiOjh9.IUI3LOxoIXqhTpmWBjSwVesSHwHU9YuE4W1f-w0FXDg

##### Answer Question #####
POST http://192.168.100.9:8080/answer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTZXNzaW9uSWQiOjEyLCJFeGFtSWQiOjh9.IUI3LOxoIXqhTpmWBjSwVesSHwHU9YuE4W1f-w0FXDg
Content-Type: application/json

{
    "question": 359,
    "option": 1433, 
    "optionChar": "A"
}

##### Clear Answer #####
DELETE http://192.168.100.9:8080/clearAnswer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTZXNzaW9uSWQiOjEyLCJFeGFtSWQiOjh9.IUI3LOxoIXqhTpmWBjSwVesSHwHU9YuE4W1f-w0FXDg

{
    "question": 359
}

##### Submit Exam #####
PUT http://192.168.100.9:8080/submitExam
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTZXNzaW9uSWQiOjEyLCJFeGFtSWQiOjh9.IUI3LOxoIXqhTpmWBjSwVesSHwHU9YuE4W1f-w0FXDg
