export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const START_EXAM = 'START_EXAM';
export const UPD_EXAM_STATUS = 'UPD_EXAM_STATUS';
export const END_EXAM = 'END_EXAM';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DECRYPT_REGISTRATION = 'DECRYPT_REGISTRATION';
export const DECRYPT_EXAM = 'DECRYPT_EXAM';
export const DISCARD_EXAM = 'DISCARD_EXAM';
export const GET_DASHBOARD = 'GET_DASHBOARD';
// export const GET_EXAMS_WITHOUT_RESPONSE_SHEET = 'GET_EXAMS_WITHOUT_RESPONSE_SHEET';
// export const GENERATE_RESPONSE_SHEET = 'GENERATE_RESPONSE_SHEET';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';